name: snow_go
description: SnowGo – snow clearing marketplace
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.17.5
  # UI
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.4.0
  geolocator: ^9.0.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.1.1
  intl: ^0.19.0
  provider: ^6.1.2
  flutter_svg: ^2.0.9
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#0E63F6"          # brand blue background
  image: assets/snowgo_splash.png  # your full logo (white or transparent works best)
#  branding: assets/snowgo_logo_white_48px.png # optional secondary mark below
  android: true
  ios: true
  web: false

  android_12:
    image: assets/snowgo_splash.png
    color: "#0E63F6"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/snowgo_splash.png
  adaptive_icon_background: "#0E63F6"   # brand blue
  adaptive_icon_foreground: assets/snowgo_splash.png

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/welcome_illustration.png
    - assets/snowgo_logo_white_24px.png
    - assets/snowgo_logo_white_48px.png
    - assets/snowgo_logo_white.png
    - assets/snowgo_mark_white_24.png
    - assets/snowgo_mark_white_28.png
    - assets/tracking.svg
    - assets/book.svg
    - assets/snowgo_splash.png
