
name: snowgo_app
description: SnowGo demo
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.17.5
  google_maps_flutter: ^2.4.0
  geolocator: ^9.0.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.1.1

flutter:
  assets:
    - assets/logo.png
    - assets/welcome_illustration.png
