import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';

import 'firebase_options.dart'; // generated by `flutterfire configure`
import 'theme/app_theme.dart';
import 'widgets/snow_overlay.dart';
import 'screens/auth/login_screen.dart';
import 'screens/home/home_screen.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const SnowGoApp());
}

class SnowGoApp extends StatelessWidget {
  const SnowGoApp({super.key});

  @override
  Widget build(BuildContext context) {
    final theme = buildAppTheme();
    return MaterialApp(
      title: 'SnowGo',
      debugShowCheckedModeBanner: false,
      theme: theme,
      home: Stack(
        children: [
          // Auth Gate: show login until authenticated
          StreamBuilder<User?>(
            stream: FirebaseAuth.instance.authStateChanges(),
            builder: (context, snap) {
              if (snap.connectionState == ConnectionState.waiting) {
                return const Scaffold(body: Center(child: CircularProgressIndicator()));
              }
              if (snap.data == null) {
                return const LoginScreen();
              }
              return const HomeScreen();
            },
          ),
          const SnowOverlay(), // subtle snow on top
        ],
      ),
    );
  }
}
